import {createFileRoute,useNavigate} from '@tanstack/react-router';
import {useState,type FormEvent} from 'react';
import {supabase} from '@/integrations/supabase/client';
import {Button} from '@/components/ui/button';
import {AdminBrand} from '@/components/admin/shared';
import {adminHead} from '@/lib/admin-briefing-fields';
import {ArrowRight,LockKeyhole} from 'lucide-react';
export const Route=createFileRoute('/admin/login')({validateSearch:(s:Record<string,unknown>)=>({denied:s.denied===true || s.denied==='true'}),head:()=>adminHead('Acesso administrativo','Acesso restrito aos briefings da Dufri Meu Negócio.'),component:AdminLogin});
function AdminLogin(){const navigate=useNavigate(); const {denied}=Route.useSearch(); const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState(denied?'Esta conta não tem permissão administrativa.':'');
 async function login(event:FormEvent){event.preventDefault();if(busy)return;setBusy(true);setError('');try{const {error:authError}=await supabase.auth.signInWithPassword({email,password});if(authError)throw authError; const {data:allowed,error:roleError}=await supabase.rpc('is_briefing_admin');if(roleError || !allowed){await supabase.auth.signOut();throw new Error('Esta conta não tem permissão administrativa.');}await navigate({to:'/admin',replace:true});}catch(e){setError(e instanceof Error?e.message:'Não foi possível entrar. Tente novamente.');}finally{setBusy(false);}}
 return <main className="min-h-dvh bg-surface px-5 py-8"><header className="mx-auto max-w-6xl"><AdminBrand/></header><section className="mx-auto w-full max-w-md py-20"><div className="aside-icon"><LockKeyhole/></div><span className="section-kicker mt-8">Área administrativa</span><h1 className="mt-4 font-display text-3xl font-bold text-primary">Acesso aos briefings</h1><form onSubmit={login} className="mt-8 space-y-5"><div><label htmlFor="email" className="mb-2 block text-sm font-bold text-primary">E-mail</label><input id="email" type="email" required autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} className="briefing-field"/></div><div><label htmlFor="password" className="mb-2 block text-sm font-bold text-primary">Senha</label><input id="password" type="password" required autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} className="briefing-field"/></div>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<Button type="submit" disabled={busy} className="action-button action-button-primary">{busy?'Entrando...':'Entrar'}<ArrowRight/></Button></form></section></main>;
}
